version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORK: landvibe
  web:
    build: ./docker/Dockerfile
    image: dstagram:latest
    ports:
      - "80:8080"
    links:
      - db:db