spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dstagram?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: cse3207
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
