spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.126.234:3306/dstagram?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: landvibe
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
